### ISSUE TITLE
Images fetched are too high resolution.

### ISSUE THREAD

**Issue by dolbyarun** [Microsoft/groove-api-sdk-csharp#16]
The images pointed by imageUrl are so huge and easily burn 200MB of data by browsing few playlist etc.

**Comment by bfreydier** [comment]
We provide the "orignal" sized image by default. In order to get ligther images, you can change the image properties (such as size) by adding parameters to the image url.

Here is our Image Service documentation: https://docs.microsoft.com/en-us/groove/using-the-groove-restful-services/image-service

**Comment by dolbyarun** [comment]
Awesome. Some how missed this in the documentation.
